### ISSUE TITLE
Installation fails when using > node v12

### ISSUE THREAD

**Issue by wboykinm** [mapbox/mbtiles-extracts#20]
`npm install mbtiles-extracts` works fine on both MacOS and Ubuntu _when using nodejs version 12 or lower_, but fails when using v14 or greater.

<details><summary>Log output</summary>

```
$ npm install mbtiles-extracts -g
npm WARN deprecated node-pre-gyp@0.11.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
/Users/bmorris/.nvm/versions/node/v14.20.1/bin/mbtiles-extracts -> /Users/bmorris/.nvm/versions/node/v14.20.1/lib/node_modules/mbtiles-extracts/mbtiles-extracts

> sqlite3@4.2.0 install /Users/bmorris/.nvm/versions/node/v14.20.1/lib/node_modules/mbtiles-extracts/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using needle for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.2.0/node-v83-darwin-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for sqlite3@4.2.0 and node@14.20.1 (node-v83 ABI, unknown) (falling back to source compile with node-gyp) 
  ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3310100/sqlite3.c
/bin/sh: python: command not found
make: *** [Release/obj/gen/sqlite-autoconf-3310100/sqlite3.c] Error 127
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/bmorris/.nvm/versions/node/v14.20.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:285:12)
gyp ERR! System Darwin 21.6.0
gyp ERR! command "/Users/bmorris/.nvm/versions/node/v14.20.1/bin/node" "/Users/bmorris/.nvm/versions/node/v14.20.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/bmorris/.nvm/versions/node/v14.20.1/lib/node_modules/mbtiles-extracts/node_modules/sqlite3/lib/binding/node-v83-darwin-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/Users/bmorris/.nvm/versions/node/v14.20.1/lib/node_modules/mbtiles-extracts/node_modules/sqlite3/lib/binding/node-v83-darwin-x64" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v83"
gyp ERR! cwd /Users/bmorris/.nvm/versions/node/v14.20.1/lib/node_modules/mbtiles-extracts/node_modules/sqlite3
gyp ERR! node -v v14.20.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/Users/bmorris/.nvm/versions/node/v14.20.1/bin/node /Users/bmorris/.nvm/versions/node/v14.20.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/bmorris/.nvm/versions/node/v14.20.1/lib/node_modules/mbtiles-extracts/node_modules/sqlite3/lib/binding/node-v83-darwin-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/Users/bmorris/.nvm/versions/node/v14.20.1/lib/node_modules/mbtiles-extracts/node_modules/sqlite3/lib/binding/node-v83-darwin-x64 --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/bmorris/.nvm/versions/node/v14.20.1/lib/node_modules/mbtiles-extracts/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1088:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:296:5)
node-pre-gyp ERR! System Darwin 21.6.0
node-pre-gyp ERR! command "/Users/bmorris/.nvm/versions/node/v14.20.1/bin/node" "/Users/bmorris/.nvm/versions/node/v14.20.1/lib/node_modules/mbtiles-extracts/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/bmorris/.nvm/versions/node/v14.20.1/lib/node_modules/mbtiles-extracts/node_modules/sqlite3
node-pre-gyp ERR! node -v v14.20.1
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok 
Failed to execute '/Users/bmorris/.nvm/versions/node/v14.20.1/bin/node /Users/bmorris/.nvm/versions/node/v14.20.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/bmorris/.nvm/versions/node/v14.20.1/lib/node_modules/mbtiles-extracts/node_modules/sqlite3/lib/binding/node-v83-darwin-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/Users/bmorris/.nvm/versions/node/v14.20.1/lib/node_modules/mbtiles-extracts/node_modules/sqlite3/lib/binding/node-v83-darwin-x64 --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sqlite3@4.2.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sqlite3@4.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/bmorris/.npm/_logs/2022-11-12T21_33_27_573Z-debug.log
```

</details>

I understand we're likely unsupported here; I just wanted to make a note of this.

**Comment by mourner** [comment]
Yeah, this package haven't been touched in a while... I think the above could be fixed by updating the `@mapbox/mbtiles` dependency to the latest version. If you need to use the package, you're welcome to update it and make a new release.
